

class Exceptions:
    def __init__(self):
        pass
    def handle_exceptions(self,e):
        pass

